name: Release to Mozilla Addon Developer Hub

on:
  workflow_dispatch:

jobs:
  release-to-mozilla:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const tagName = latestRelease.data.tag_name;
            return tagName.startsWith('v') ? tagName.substring(1) : tagName;
          result-encoding: string

      - name: Download Firefox Artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow_search: true
          search_artifacts: true
          branch: ${{ github.ref }}
          name: crunchy-comments-${{ steps.get_release.outputs.result }}
          path: ./artifacts

      - name: Publish to Mozilla Addon Developer Hub
        uses: wdzeng/firefox-addon@v1.0.5
        with:
          addon-guid: ${{ vars.MOZILLA_ADDON_GUID }}
          xpi-path: ./artifacts/crunchy-comments-${{ steps.get_release.outputs.result }}-firefox.zip
          self-hosted: false    
          jwt-issuer: ${{ secrets.MOZILLA_JWT_ISSUER }}
          jwt-secret: ${{ secrets.MOZILLA_JWT_SECRET }}
